name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [main, release/paclet]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}

jobs:

  Build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    container:
      image: wolframresearch/wolframengine:13.3
      options: --user root

    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check
      run: wolframscript -f Scripts/CheckPaclet.wls

    - name: Build
      run: wolframscript -f Scripts/BuildPaclet.wls

    - name: UploadArtifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{ env.PACLET_BUILD_DIR }}
    
    - name: Test
      run: wolframscript -f Scripts/TestPaclet.wls

    - name: Upload stack data
      if: always() && env.PACLET_STACK_HISTORY
      uses: actions/upload-artifact@v3
      with:
        name: test-paclet-stacks-${{ env.WOLFRAM_SYSTEM_ID }}
        path: ${{ env.PACLET_STACK_HISTORY }}
        retention-days: 1
        if-no-files-found: error