name: Build

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}

jobs:

  Build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    container:
      image: wolframresearch/wolframengine:latest
      options: --user root

    env:
      WOLFRAM_SYSTEM_ID: Linux-x86-64

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: BuildMX
      run: wolframscript -f Scripts/BuildMX.wls

    - name: Build
      uses: WolframResearch/build-paclet@v1.10.2

    - name: UploadArtifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{ env.PACLET_BUILD_DIR }}