name: Check
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
env:
  RESOURCE_PUBLISHER_TOKEN: ${{ secrets.RESOURCE_PUBLISHER_TOKEN }}
  WOLFRAMSCRIPT_ENTITLEMENTID: ${{ secrets.WOLFRAMSCRIPT_ENTITLEMENTID }}
jobs:
  Check:
    name: Check
    runs-on: ubuntu-latest
    container:
      image: wolframresearch/wolframengine:13.2.0
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: BuildMX
      run: wolframscript -f Scripts/BuildMX.wls
    - name: Build
      uses: WolframResearch/build-paclet@v1.10.2
    - name: UploadArtifact
      uses: actions/upload-artifact@v3
      with:
        path: ${{ env.PACLET_BUILD_DIR }}